# Generated by Django 4.0.1 on 2022-01-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='react',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
